export type MK04Status = 'DRAFT' | 'VERIFIED' | 'LOCKED';

export interface ChiSoKenh {
  id: string;
  organization_id: string;
  channel_id: string;
  period_start: string;
  period_end: string;
  total_cost: number;
  valid_leads: number;
  cpl_vnd: number | null;
  status: MK04Status;
  revision: number;
  row_version: number;
}

export class MK04Error extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'MK04Error';
  }
}

export const mk04Domain = {
  calculateCPL(totalCost: number, validLeads: number): number | null {
    if (validLeads <= 0) return null;
    return totalCost / validLeads;
  },

  tongHopKenh(channel_id: string, period_start: string, period_end: string, total_cost: number, valid_leads: number, existingRecord?: ChiSoKenh): ChiSoKenh {
    if (existingRecord && existingRecord.status === 'LOCKED') {
      throw new MK04Error('Không thể tổng hợp lại dữ liệu đã khóa (LOCKED)');
    }

    const cpl_vnd = this.calculateCPL(total_cost, valid_leads);

    if (existingRecord) {
      return {
        ...existingRecord,
        total_cost,
        valid_leads,
        cpl_vnd,
        status: 'DRAFT',
        revision: existingRecord.revision + 1,
        row_version: existingRecord.row_version + 1
      };
    }

    return {
      id: '', // Generated by DB
      organization_id: '', // Filled by backend
      channel_id,
      period_start,
      period_end,
      total_cost,
      valid_leads,
      cpl_vnd,
      status: 'DRAFT',
      revision: 1,
      row_version: 1
    };
  },

  changeStatus(record: ChiSoKenh, newStatus: MK04Status): ChiSoKenh {
    if (record.status === 'LOCKED') {
      throw new MK04Error('Không thể đổi trạng thái của bản ghi đã khóa');
    }

    const allowedTransitions: Record<MK04Status, MK04Status[]> = {
      'DRAFT': ['VERIFIED'],
      'VERIFIED': ['LOCKED', 'DRAFT'],
      'LOCKED': []
    };

    if (!allowedTransitions[record.status].includes(newStatus)) {
      throw new MK04Error(`Không thể chuyển trạng thái từ ${record.status} sang ${newStatus}`);
    }

    return {
      ...record,
      status: newStatus,
      row_version: record.row_version + 1
    };
  }
};
